<a href="https://colab.research.google.com/github/SoupBoi1/TLS-Fingerprinting-Malicious-Detection/blob/main/TLSMaliciousDetection.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#TLSFingerprintingMaliciousDetectionNotebook1

#author Matt Lutjen, Brady Bangasser, Sudipta Halder,

#Importing data and libs

In [ ]:
#!pip install darts
!pip install optuna
!pip install optuna-dashboard
!pip install lime
!pip install imbalanced-learn
!pip install xgboost

Collecting optuna
  Using cached optuna-4.8.0-py3-none-any.whl.metadata (17 kB)
Collecting alembic>=1.5.0 (from optuna)
  Using cached alembic-1.18.4-py3-none-any.whl.metadata (7.2 kB)
Collecting colorlog (from optuna)
  Using cached colorlog-6.10.1-py3-none-any.whl.metadata (11 kB)
Requirement already satisfied: numpy in ./.venv/lib/python3.10/site-packages (from optuna) (1.26.4)
Requirement already satisfied: packaging>=20.0 in ./.venv/lib/python3.10/site-packages (from optuna) (26.0)
Collecting sqlalchemy>=1.4.2 (from optuna)
  Using cached sqlalchemy-2.0.49-cp310-cp310-macosx_11_0_arm64.whl.metadata (9.5 kB)
Requirement already satisfied: tqdm in ./.venv/lib/python3.10/site-packages (from optuna) (4.67.3)
Requirement already satisfied: PyYAML in ./.venv/lib/python3.10/site-packages (from optuna) (6.0.3)
Collecting Mako (from alembic>=1.5.0->optuna)
  Using cached mako-1.3.12-py3-none-any.whl.metadata (2.9 kB)
Requirement already satisfied: typing-extensions>=4.12 in ./.venv/lib/python3.10/site-packages (from alembic>=1.5.0->optuna) (4.15.0)
Collecting tomli (from alembic>=1.5.0->optuna)
  Using cached tomli-2.4.1-py3-none-any.whl.metadata (10 kB)
Requirement already satisfied: MarkupSafe>=0.9.2 in ./.venv/lib/python3.10/site-packages (from Mako->alembic>=1.5.0->optuna) (3.0.3)
Using cached optuna-4.8.0-py3-none-any.whl (419 kB)
Using cached alembic-1.18.4-py3-none-any.whl (263 kB)
Using cached sqlalchemy-2.0.49-cp310-cp310-macosx_11_0_arm64.whl (2.2 MB)
Using cached colorlog-6.10.1-py3-none-any.whl (11 kB)
Using cached mako-1.3.12-py3-none-any.whl (78 kB)
Using cached tomli-2.4.1-py3-none-any.whl (14 kB)
Installing collected packages: tomli, sqlalchemy, Mako, colorlog, alembic, optuna
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6/6 [optuna]2m5/6 [optuna]]my]
Successfully installed Mako-1.3.12 alembic-1.18.4 colorlog-6.10.1 optuna-4.8.0 sqlalchemy-2.0.49 tomli-2.4.1
Collecting optuna-dashboard
  Using cached optuna_dashboard-0.20.0-py3-none-any.whl.metadata (6.7 kB)
Collecting bottle>=0.13.0 (from optuna-dashboard)
  Using cached bottle-0.13.4-py2.py3-none-any.whl.metadata (1.6 kB)
Requirement already satisfied: optuna>=3.6.0 in ./.venv/lib/python3.10/site-packages (from optuna-dashboard) (4.8.0)
Requirement already satisfied: tomli in ./.venv/lib/python3.10/site-packages (from optuna-dashboard) (2.4.1)
Requirement already satisfied: alembic>=1.5.0 in ./.venv/lib/python3.10/site-packages (from optuna>=3.6.0->optuna-dashboard) (1.18.4)
Requirement already satisfied: colorlog in ./.venv/lib/python3.10/site-packages (from optuna>=3.6.0->optuna-dashboard) (6.10.1)
Requirement already satisfied: numpy in ./.venv/lib/python3.10/site-packages (from optuna>=3.6.0->optuna-dashboard) (1.26.4)
Requirement already satisfied: packaging>=20.0 in ./.venv/lib/python3.10/site-packages (from optuna>=3.6.0->optuna-dashboard) (26.0)
Requirement already satisfied: sqlalchemy>=1.4.2 in ./.venv/lib/python3.10/site-packages (from optuna>=3.6.0->optuna-dashboard) (2.0.49)
Requirement already satisfied: tqdm in ./.venv/lib/python3.10/site-packages (from optuna>=3.6.0->optuna-dashboard) (4.67.3)
Requirement already satisfied: PyYAML in ./.venv/lib/python3.10/site-packages (from optuna>=3.6.0->optuna-dashboard) (6.0.3)
Requirement already satisfied: Mako in ./.venv/lib/python3.10/site-packages (from alembic>=1.5.0->optuna>=3.6.0->optuna-dashboard) (1.3.12)
Requirement already satisfied: typing-extensions>=4.12 in ./.venv/lib/python3.10/site-packages (from alembic>=1.5.0->optuna>=3.6.0->optuna-dashboard) (4.15.0)
Requirement already satisfied: MarkupSafe>=0.9.2 in ./.venv/lib/python3.10/site-packages (from Mako->alembic>=1.5.0->optuna>=3.6.0->optuna-dashboard) (3.0.3)
Using cached optuna_dashboard-0.20.0-py3-none-any.whl (8.4 MB)
Using cached bottle-0.13.4-py2.py3-none-any.whl (103 kB)
Installing collected packages: bottle, optuna-dashboard
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2/2 [optuna-dashboard]
Successfully installed bottle-0.13.4 optuna-dashboard-0.20.0

In [ ]:
import optuna

/Users/sudiptahalder/Documents/school/TLS-Fingerprinting-Malicious-Detection/.venv/lib/python3.10/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [ ]:
import numpy as np
import json
import pandas as pd
import matplotlib.pyplot as plt
import requests

In [ ]:


#preprocessing
from sklearn.preprocessing import normalize
from sklearn.preprocessing import OrdinalEncoder
from sklearn.preprocessing import TargetEncoder
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import LabelBinarizer
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import OneHotEncoder
from sklearn.pipeline import Pipeline
from sklearn.linear_model import LogisticRegression


#imbalance
from sklearn.impute import SimpleImputer
from imblearn.datasets import make_imbalance
from imblearn.under_sampling import RandomUnderSampler
from imblearn.over_sampling import RandomOverSampler
from imblearn.over_sampling import SMOTE
from imblearn.under_sampling import TomekLinks


#datasets
from sklearn.datasets import load_iris
from imblearn.datasets import make_imbalance
from sklearn.datasets import make_classification
from sklearn.base import BaseEstimator, ClassifierMixin, RegressorMixin

from sklearn.model_selection import train_test_split


#imbalanced learning
from imblearn.under_sampling import RandomUnderSampler
from imblearn.over_sampling import RandomOverSampler
from imblearn.over_sampling import SMOTE
from imblearn.under_sampling import TomekLinks


#models
from sklearn.decomposition import PCA
from sklearn.cluster import KMeans
from sklearn.linear_model import LinearRegression
from sklearn import tree
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import OneClassSVM
from sklearn.neural_network import MLPClassifier
from sklearn.svm import OneClassSVM


#matrics
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, roc_auc_score
from sklearn.metrics import roc_auc_score
from sklearn.metrics import precision_recall_curve, auc
from sklearn.metrics import average_precision_score
from sklearn.metrics import adjusted_rand_score,normalized_mutual_info_score
from sklearn.metrics import silhouette_score
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, roc_curve, auc, ConfusionMatrixDisplay

from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.model_selection import cross_val_score


#interpretability
import lime
import lime.lime_tabular

import seaborn as sns

In [ ]:
import tensorflow as tf
from tensorflow import keras

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import BatchNormalization,Dense, Conv2D, Flatten, Reshape
from tensorflow.keras.layers import Activation
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.layers import Input
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv1D, MaxPooling1D, Flatten, Dense
from tensorflow.keras.layers import Dropout
from tensorflow.keras.layers import BatchNormalization

In [ ]:
print("Num GPUs Available: ", len(tf.config.list_physical_devices('GPU')))

Num GPUs Available:  1

In [ ]:
seed = 2
random.seed(seed)
np.random.seed(seed)
# Recommended for modern NumPy
# rng = np.random.default_rng(seed)
os.environ['PYTHONHASHSEED'] = str(seed)

In [ ]:
df = pd.read_csv('https://raw.githubusercontent.com/SoupBoi1/TLS-Fingerprinting-Malicious-Detection/refs/heads/main/dataset/dataset.csv')#getting the data

In [ ]:

display(df.head())

,SrcPort,SNI,AppName,DstPort,JA3Shash,JA3hash,JA4hash,Type,SrcIP,Version,Filename,OrgName,DstIP,JA4Shash,Label,Attack
0,58688,officehymy.com,sodinokibi,443,61be9ce3d068c08ff99a857f62352f9d,a0e9f5d64349fb13191bc781f81f42e1,t12d190800_d83cc789557e_7af1ed941c26,M,10.127.0.109,0.0,tests/malware2/SODINOKIBI/240602-km899agd6t.be...,Japan Network Information Center; XSERVER20 (JP),157.112.183.48,t120400_c02f_460f64128655,SODINOKIBI,1
1,51187,sf16-muse-va.ibytedtos.com,star_quiz_01,443,42ec7b1db61428bf1cc6e01b9ef02b04,6ec2896feff5746955f700c0023f5804,t12d1409h1_c866b44c5a26_b39be8c56a14,M,192.168.0.100,0.0,tests/malware4/android11/star_quiz_01-extracte...,Slovak Telecom Network Administrator; BA-WEBHO...,212.5.219.10,t1206h1_c02c_e1dda4771ae8,MALWARE,1
2,61625,avatars.mds.yandex.net,zloader,443,4ee87de303b9c8138441e6527cbeea3e,cd08e31494f9531f560d64c695473da9,t13d1516h2_8daaf6152771_e5627efa2ab1,M,10.127.0.108,0.0,tests/malware2/ZLOADER/240525-adwbxsga76.behav...,YANDEX LLC; YANDEX-87-250-247 (RU),87.250.247.182,t1304h2_1302_a56c5b993250,ZLOADER,1
3,50972,js.stripe.com,asyncrat,443,60c22edca21e0598ad28f8d78c8dedcd,579ccef312d18482fc42e2b822ca2430,t13d1715h2_5b57614c22b0_a815a0c236aa,M,10.127.0.20,0.0,tests/malware2/ASYNCRAT/240608-e15lbsgh9x.beha...,Amazon.com; Inc.; AMAZON-CF,18.245.86.52,t1304h2_1301_a56c5b993250,ASYNCRAT,1
4,50579,rps-svcs.oracle.com,bazarbackdoor,443,a860078aa51e1102b117d1f8a1437b72,2a458dd9c65afbcf591cd8c2a194b804,t12d210600_b973bfd88a0e_1da50ec048a3,M,10.127.0.3,0.0,tests/malware2/BAZARBACKDOOR/230429-ytv8vsbh95...,Akamai International; BV; AIBV,23.222.50.60,t120400_c014_cbb8871a0652,BAZARBACKDOOR,1

In [ ]:
df.info()#info
df.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30664 entries, 0 to 30663
Data columns (total 16 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   SrcPort   30664 non-null  int64
 1   SNI       30239 non-null  object
 2   AppName   30664 non-null  object
 3   DstPort   30664 non-null  int64
 4   JA3Shash  28951 non-null  object
 5   JA3hash   30664 non-null  object
 6   JA4hash   30664 non-null  object
 7   Type      30414 non-null  object
 8   SrcIP     30664 non-null  object
 9   Version   28951 non-null  float64
 10  Filename  28951 non-null  object
 11  OrgName   30664 non-null  object
 12  DstIP     30664 non-null  object
 13  JA4Shash  28951 non-null  object
 14  Label     29149 non-null  object
 15  Attack    30664 non-null  int64
dtypes: float64(1), int64(3), object(12)
memory usage: 3.7+ MB

            SrcPort       DstPort  Version        Attack
count  30664.000000  30664.000000  28951.0  30664.000000
mean   55442.169482    583.606933      0.0      0.787666
std     4529.980500   1485.352244      0.0      0.408966
min    33139.000000     80.000000      0.0      0.000000
25%    51291.750000    443.000000      0.0      1.000000
50%    54972.500000    443.000000      0.0      1.000000
75%    58615.250000    443.000000      0.0      1.000000
max    65533.000000  49816.000000      0.0      1.000000

In [ ]:
df["DstIP"].unique()

array(['157.112.183.48', '212.5.219.10', '87.250.247.182', ...,
       '52.26.253.153', '2.22.89.33', '66.70.219.208'], dtype=object)

#Pre-possessing and Data Analysis

encoding and spliting the IPs

In [ ]:
SrcIP_1=[]
SrcIP_2=[]
SrcIP_3=[]
SrcIP_4=[]
for i in df["SrcIP"]:

  #print(i.split('.'))
  SrcIP_1.append(int(i.split('.')[0]))
  SrcIP_2.append(int(i.split('.')[1]))
  SrcIP_3.append(int(i.split('.')[2]))
  SrcIP_4.append(int(i.split('.')[3]))
print(np.shape(SrcIP_1))
print(np.shape(SrcIP_2))
print(np.shape(SrcIP_3))
print(np.shape(SrcIP_4))

(30664,)
(30664,)
(30664,)
(30664,)

In [ ]:
DstIP_1=[]
DstIP_2=[]
DstIP_3=[]
DstIP_4=[]
for i in df["DstIP"]:

  #print(i.split('.'))
  DstIP_1.append(int(i.split('.')[0]))
  DstIP_2.append(int(i.split('.')[1]))
  DstIP_3.append(int(i.split('.')[2]))
  DstIP_4.append(int(i.split('.')[3]))

jA4

In [ ]:
def JA4_parameters_extration(JA4_A):
  protocal,TLS_version,SNI,Nciper,Nextension,ALPN=None,None,None,None,None,None
  if(len(JA4_A)==10):
    protocal=JA4_A[0]
    TLS_version=(JA4_A[1:3])
    SNI=JA4_A[3]
    Nciper=int(JA4_A[4:6])
    Nextension=int(JA4_A[6:7])
    ALPN=JA4_A[8:]
  return [protocal,TLS_version,SNI,Nciper,Nextension,ALPN]

def JA4S_parameters_extration(JA4S_A):
  protocal,TLS_version,Nextension,ALPN=None,None,None,None
  if(len(JA4S_A)==7):
    protocal=JA4S_A[0]
    TLS_version=(JA4S_A[1:3])
    Nextension=int(JA4S_A[3:5])
    ALPN=JA4S_A[5:]
  return [protocal,TLS_version,Nextension,ALPN]

def JA4H_parameters_extration(JA4H_A):
  method,version,cookie,ref,NHeaders,AL=None,None,None,None,None,None
  if(len(JA4H_A)==12):
    method=JA4H_A[0:2]
    version=(JA4H_A[2:4])
    cookie=JA4H_A[4]
    ref=JA4H_A[5]
    NHeaders=JA4H_A[6:8]
    AL=JA4H_A[8:]
  return [method,version,cookie,ref,NHeaders,AL]

print(np.array(JA4_parameters_extration('t13d1516h2')))
print(JA4S_parameters_extration('t120400'))
print(JA4H_parameters_extration('ge20cr13enus'))

['t' '13' 'd' '15' '1' 'h2']
['t', '12', 4, '00']
['ge', '20', 'c', 'r', '13', 'enus']

In [ ]:
JA4A=[]
JA4B=[]
JA4C=[]
Protocal =[]
TLS_Version =[]
Nextension=[]
SNI= []
Nciper=[]
ALPN =[]

for i in df["JA4hash"]:
  array = JA4_parameters_extration(i.split('_')[0])
  Protocal.append(array[0])
  TLS_Version.append(array[1])
  SNI.append(array[2])
  Nciper.append(array[3])
  Nextension.append(array[4])
  ALPN.append(array[5])
  #print(i.split('.'))
  JA4A.append(i.split('_')[0])
  JA4B.append(i.split('_')[1])
  JA4C.append(i.split('_')[2])

In [ ]:
JA4SA=[]
JA4SB=[]
JA4SC=[]
ProtocalS =[]
TLS_VersionS =[]
NextensionS=[]
ALPNS =[]

for i in df["JA4Shash"]:

  if i is not None and type(i)==str:
      array = JA4S_parameters_extration(i.split('_')[0])
      ProtocalS.append(array[0])
      TLS_VersionS.append(array[1])
      NextensionS.append(array[2])
      ALPNS.append(array[3])

      JA4SA.append(i.split('_')[0])
      JA4SB.append(i.split('_')[1])
      JA4SC.append(i.split('_')[2])
  else:
    #print(i)
    ProtocalS.append(None)
    TLS_VersionS.append(None)
    NextensionS.append(None)
    ALPNS.append(None)
    JA4SA.append(None)
    JA4SB.append(None)
    JA4SC.append(None)

## 60/20/20 split

In [ ]:


features_df = pd.DataFrame({

    'SrcIP_1': SrcIP_1, 'SrcIP_2': SrcIP_2, 'SrcIP_3': SrcIP_3, 'SrcIP_4': SrcIP_4,

    'DstIP_1': DstIP_1, 'DstIP_2': DstIP_2, 'DstIP_3': DstIP_3, 'DstIP_4': DstIP_4,

    'JA4_protocal':Protocal, 'JA4_TLS_version':TLS_Version,'JA4_SNI':SNI,'JA4_Nciper':Nciper ,'JA4_Nextension':Nextension , 'JA4_ALPN':ALPN, 'JA4B': JA4B, 'JA4C': JA4C,

     'JA4S_Protocal': ProtocalS, 'JA4S_TLS_Version': TLS_VersionS, 'JA4S_Nextension': NextensionS, 'JA4S_ALPNS': ALPNS, 'JA4SB': JA4SB, 'JA4SC': JA4SC,

    'SrcPort': df['SrcPort'],

    'DstPort': df['DstPort']#,'Attack': df['Attack']

})

In [ ]:
hotencode_labels = ['JA4_TLS_version', 'JA4S_TLS_Version', 'JA4B', 'JA4C', 'JA4SB', 'JA4SC']

In [ ]:

X_tempR, X_testR, y_tempR, y_test = train_test_split(features_df, df['Attack'].values, test_size=0.20, random_state=42, stratify=df['Attack'].values)

X_trainR, X_valR, y_train, y_val = train_test_split(X_tempR, y_tempR, test_size=0.25, random_state=42, stratify=y_tempR)

print(f"Training set size: {X_trainR.shape[0]}")

print(f"Validation set size: {X_valR.shape[0]}")

print(f"Testing set size: {X_testR.shape[0]}")

Training set size: 18398
Validation set size: 6133
Testing set size: 6133

In [ ]:
X_trainR.columns

Index(['SrcIP_1', 'SrcIP_2', 'SrcIP_3', 'SrcIP_4', 'DstIP_1', 'DstIP_2',
       'DstIP_3', 'DstIP_4', 'JA4_protocal', 'JA4_TLS_version', 'JA4_SNI',
       'JA4_Nciper', 'JA4_Nextension', 'JA4_ALPN', 'JA4B', 'JA4C',
       'JA4S_Protocal', 'JA4S_TLS_Version', 'JA4S_Nextension', 'JA4S_ALPNS',
       'JA4SB', 'JA4SC', 'SrcPort', 'DstPort'],
      dtype='object')

In [ ]:
X_trainR.select_dtypes(include=[np.number]).head()

,SrcIP_1,SrcIP_2,SrcIP_3,SrcIP_4,DstIP_1,DstIP_2,DstIP_3,DstIP_4,JA4_Nciper,JA4_Nextension,JA4S_Nextension,SrcPort,DstPort
11659,10,127,0,238,104,19,222,79,12.0,0.0,NaN,49538,443
24143,10,127,0,65,185,199,108,154,15.0,1.0,2.0,49858,443
4509,10,127,0,253,78,40,8,65,12.0,0.0,NaN,50276,443
12177,10,127,0,120,104,21,235,132,12.0,0.0,3.0,49745,443
22573,192,168,3,28,142,251,37,99,17.0,1.0,2.0,59477,443

In [ ]:
X_trainR.loc[:, ~X_trainR.columns.isin(hotencode_labels)].select_dtypes(exclude=[np.number]).head()

      JA4_protocal JA4_SNI JA4_ALPN JA4S_Protocal JA4S_ALPNS
11659            t       d       00          None       None
24143            t       d       h2             t         00
4509             t       d       00          None       None
12177            t       d       00             t         00
22573            t       d       h1             t         00

In [ ]:
X_trainR.loc[:, X_trainR.columns.isin(hotencode_labels)].head()

,JA4_TLS_version,JA4B,JA4C,JA4S_TLS_Version,JA4SB,JA4SC
11659,10,d94e65cdb899,5f12c91e28fe,None,None,None
24143,13,8daaf6152771,e5627efa2ab1,13,1301,a56c5b993250
4509,10,d94e65cdb899,5f12c91e28fe,None,None,None
12177,10,d94e65cdb899,5f12c91e28fe,10,c009,344b4dce5a52
22573,13,5b57614c22b0,eca864cca44a,13,1301,234ea6891581

In [ ]:
label_trainR = X_trainR.loc[:, ~X_trainR.columns.isin(hotencode_labels)].select_dtypes(exclude=[np.number])
label_testR = X_testR.loc[:, ~X_testR.columns.isin(hotencode_labels)].select_dtypes(exclude=[np.number])
label_valR = X_valR.loc[:, ~X_valR.columns.isin(hotencode_labels)].select_dtypes(exclude=[np.number])

In [ ]:
hotencoding_trainR= X_trainR.loc[:, X_trainR.columns.isin(hotencode_labels)]
hotencoding_testR = X_testR.loc[:, X_testR.columns.isin(hotencode_labels)]
hotencoding_valR = X_valR.loc[:, X_valR.columns.isin(hotencode_labels)]

### encoding

#### numeric

In [ ]:

numeric_pipeline = Pipeline([
    ('imputer', SimpleImputer(strategy='median')),
    ('scaler', StandardScaler())
])


numeric_pipeline.fit(np.zeros([10,10]))

Pipeline(steps=[('imputer', SimpleImputer(strategy='median')),
                ('scaler', StandardScaler())])

In [ ]:
X_train_num_t = X_trainR.select_dtypes(include=[np.number])
numeric_pipeline.fit(X_train_num_t)
X_train_num = numeric_pipeline.transform(X_train_num_t)

X_val_num_t = X_valR.select_dtypes(include=[np.number])
#numeric_pipeline.fit(X_val_num_t)
X_val_num = numeric_pipeline.transform(X_val_num_t)

X_test_num_t = X_testR.select_dtypes(include=[np.number])
#numeric_pipeline.fit(X_test_num_t)
X_test_num = numeric_pipeline.transform(X_test_num_t)

#### *categorical*

In [ ]:
categorical_pipeline = Pipeline([
    ('imputer', SimpleImputer(strategy='most_frequent')),
    ('encoder', OneHotEncoder(handle_unknown='ignore'))
])

In [ ]:
categorical_pipeline.fit(hotencoding_trainR)
X_train_cat = categorical_pipeline.transform(hotencoding_trainR)


X_val_cat = categorical_pipeline.transform(hotencoding_testR)

X_test_cat = categorical_pipeline.transform(hotencoding_valR)

#### Label based

In [ ]:
label_pipeline = Pipeline([
    ('imputer', SimpleImputer(strategy='most_frequent')),
    ('encoder', OrdinalEncoder())
])

In [ ]:
label_pipeline.fit(label_trainR)
X_train_label = label_pipeline.transform(label_trainR)


X_val_label = label_pipeline.transform(label_testR)

X_test_label = label_pipeline.transform(label_valR)

In [ ]:
X_train = np.concatenate((X_train_num, X_train_cat.toarray(),X_train_label), axis=1)
X_val = np.concatenate((X_val_num, X_val_cat.toarray(),X_val_label), axis=1)
X_test = np.concatenate((X_test_num, X_test_cat.toarray(),X_test_label), axis=1)

### Data Balancing with SMOTE
SMOTE is applied **only** to the training split to prevent data leakage into validation/test sets.

In [ ]:
# ── SMOTE: Balance the training set (applied ONLY to training data) ──
print("Class distribution before SMOTE:", dict(zip(*np.unique(y_train, return_counts=True))))

smote = SMOTE(random_state=42)
X_train_resampled, y_train_resampled = smote.fit_resample(X_train, y_train)

print("Class distribution after SMOTE: ", dict(zip(*np.unique(y_train_resampled, return_counts=True))))
print(f"X_train shape before SMOTE: {X_train.shape} → after: {X_train_resampled.shape}")

# Model Cration, Training, Validation,Testing

In [ ]:
import joblib
import os

In [ ]:
print("--- STARTING MANUAL LOOP TUNING ---")

best_models = {}
predictions = {}

--- STARTING MANUAL LOOP TUNING ---

In [ ]:
print("\n1. Tuning Decision Tree with loops...")
best_dt_acc = 0
best_dt_model = None
best_dt_params = {}

for depth in [None, 10, 20]:
    for min_samples in [2, 5, 10]:
        model = DecisionTreeClassifier(max_depth=depth, min_samples_split=min_samples, random_state=42)
        model.fit(X_train_resampled, y_train_resampled)

        os.makedirs('saved_models/decision_tree', exist_ok=True)
        filename = f"saved_models/decision_tree/decision_tree_min_samples_split_{min_samples}_depth_{depth}.joblib"
        joblib.dump(model, filename)
        print(f"Saved: {filename}")

        val_preds = model.predict(X_val)
        val_acc = accuracy_score(y_val, val_preds)

        if val_acc > best_dt_acc:
            best_dt_acc = val_acc
            best_dt_model = model
            best_dt_params = {'max_depth': depth, 'min_samples_split': min_samples}

best_models['Decision Tree'] = best_dt_model
print(f"Best DT Params: {best_dt_params} | Val Accuracy: {best_dt_acc:.4f}")

1. Tuning Decision Tree with loops...
Saved: saved_models/decision_tree/decision_tree_min_samples_split_2_depth_None.joblib
Saved: saved_models/decision_tree/decision_tree_min_samples_split_5_depth_None.joblib
Saved: saved_models/decision_tree/decision_tree_min_samples_split_10_depth_None.joblib
Saved: saved_models/decision_tree/decision_tree_min_samples_split_2_depth_10.joblib
Saved: saved_models/decision_tree/decision_tree_min_samples_split_5_depth_10.joblib
Saved: saved_models/decision_tree/decision_tree_min_samples_split_10_depth_10.joblib
Saved: saved_models/decision_tree/decision_tree_min_samples_split_2_depth_20.joblib
Saved: saved_models/decision_tree/decision_tree_min_samples_split_5_depth_20.joblib
Saved: saved_models/decision_tree/decision_tree_min_samples_split_10_depth_20.joblib
Best DT Params: {'max_depth': None, 'min_samples_split': 2} | Val Accuracy: 0.8120

In [ ]:
print("\n2. Tuning Random Forest with loops...")
best_rf_acc = 0
best_rf_model = None
best_rf_params = {}

for n_trees in [50, 100]:
    for depth in [None, 10, 20]:
        model = RandomForestClassifier(n_estimators=n_trees, max_depth=depth, random_state=42)
        model.fit(X_train_resampled, y_train_resampled)

        os.makedirs('saved_models/random_forest', exist_ok=True)
        filename = f"saved_models/random_forest/rf_trees_n_estimators_{n_trees}_max_depth_{depth}.joblib"
        joblib.dump(model, filename)
        print(f"Saved: {filename}")

        val_preds = model.predict(X_val)
        val_acc = accuracy_score(y_val, val_preds)

        if val_acc > best_rf_acc:
            best_rf_acc = val_acc
            best_rf_model = model
            best_rf_params = {'n_estimators': n_trees, 'max_depth': depth}

best_models['Random Forest'] = best_rf_model
print(f"Best RF Params: {best_rf_params} | Val Accuracy: {best_rf_acc:.4f}")

2. Tuning Random Forest with loops...
Saved: saved_models/random_forest/rf_trees_min_samples_10_depth_None.joblib
Saved: saved_models/random_forest/rf_trees_min_samples_10_depth_10.joblib
Saved: saved_models/random_forest/rf_trees_min_samples_10_depth_20.joblib
Saved: saved_models/random_forest/rf_trees_min_samples_10_depth_None.joblib
Saved: saved_models/random_forest/rf_trees_min_samples_10_depth_10.joblib
Saved: saved_models/random_forest/rf_trees_min_samples_10_depth_20.joblib
Best RF Params: {'n_estimators': 100, 'max_depth': 10} | Val Accuracy: 0.8202

In [ ]:
print("\n3. Tuning MLP Classifier with loops...")
best_mlp_acc = 0
best_mlp_model = None
best_mlp_params = {}

for hidden_layer in [(50,), (100,), (50, 50)]:
    for activation_func in ['relu', 'tanh']:
        model = MLPClassifier(hidden_layer_sizes=hidden_layer, activation=activation_func, max_iter=300, random_state=42)
        model.fit(X_train_resampled, y_train_resampled)

        os.makedirs('saved_models/MLP', exist_ok=True)
        filename = f"saved_models/MLP/MLP_hidden_layer_sizes_{hidden_layer}_activation_func_{activation_func}.joblib"
        joblib.dump(model, filename)
        print(f"Saved: {filename}")

        val_preds = model.predict(X_val)
        val_acc = accuracy_score(y_val, val_preds)

        if val_acc > best_mlp_acc:
            best_mlp_acc = val_acc
            best_mlp_model = model
            best_mlp_params = {'hidden_layer_sizes': hidden_layer, 'activation': activation_func}

best_models['MLP'] = best_mlp_model
print(f"Best MLP Params: {best_mlp_params} | Val Accuracy: {best_mlp_acc:.4f}")

3. Tuning MLP Classifier with loops...
Saved: saved_models/MLP/MLP_hidden_layer_sizes_(50,)_activation_func_relu.joblib

/Users/sudiptahalder/Documents/school/TLS-Fingerprinting-Malicious-Detection/.venv/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (300) reached and the optimization hasn't converged yet.
  warnings.warn(

Saved: saved_models/MLP/MLP_hidden_layer_sizes_(50,)_activation_func_tanh.joblib
Saved: saved_models/MLP/MLP_hidden_layer_sizes_(100,)_activation_func_relu.joblib
Saved: saved_models/MLP/MLP_hidden_layer_sizes_(100,)_activation_func_tanh.joblib
Saved: saved_models/MLP/MLP_hidden_layer_sizes_(50, 50)_activation_func_relu.joblib
Saved: saved_models/MLP/MLP_hidden_layer_sizes_(50, 50)_activation_func_tanh.joblib
Best MLP Params: {'hidden_layer_sizes': (50,), 'activation': 'relu'} | Val Accuracy: 0.8130

In [ ]:
print("\n4. Tuning CNN with loops...")

X_train_cnn = X_train_resampled.reshape(X_train_resampled.shape[0], X_train_resampled.shape[1], 1)
X_val_cnn = X_val.reshape(X_val.shape[0], X_val.shape[1], 1)
X_test_cnn = X_test.reshape(X_test.shape[0], X_test.shape[1], 1)

best_cnn_acc = 0
best_cnn_model = None
best_cnn_params = {}

from tensorflow.keras.callbacks import EarlyStopping

for filters in [32, 64]:
    for dense_units in [32, 64]:
        print(f"   -> Training CNN with {filters} filters, {dense_units} dense units...")

        model = Sequential([
            Conv1D(filters=filters, kernel_size=3, activation='relu', input_shape=(X_train_cnn.shape[1], 1)),
            MaxPooling1D(pool_size=2),
            Flatten(),
            Dense(dense_units, activation='relu'),
            Dropout(0.5),
            Dense(1, activation='sigmoid')
        ])

        model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

        early_stop = EarlyStopping(monitor='val_loss', patience=3, restore_best_weights=True)

        model.fit(
            X_train_cnn, y_train_resampled,
            epochs=50, batch_size=32, verbose=0,
            validation_data=(X_val_cnn, y_val),
            callbacks=[early_stop]
        )

        os.makedirs('saved_models/cnn', exist_ok=True)
        model_name = f"saved_models/cnn/cnn_f{filters}_d{dense_units}.keras"
        model.save(model_name)
        print(f"      Saved model to: {model_name}")

        loss, val_acc = model.evaluate(X_val_cnn, y_val, verbose=0)

        if val_acc > best_cnn_acc:
            best_cnn_acc = val_acc
            best_cnn_model = model
            best_cnn_params = {'filters': filters, 'dense_units': dense_units}

best_models['CNN'] = best_cnn_model
print(f"Best CNN Params: {best_cnn_params} | Val Accuracy: {best_cnn_acc:.4f}")

4. Tuning CNN with loops...
   -> Training CNN with 32 filters, 32 dense units...

/Users/sudiptahalder/Documents/school/TLS-Fingerprinting-Malicious-Detection/.venv/lib/python3.10/site-packages/keras/src/layers/convolutional/base_conv.py:113: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)
2026-05-02 17:35:43.030406: I metal_plugin/src/device/metal_device.cc:1154] Metal device set to: Apple M1 Pro
2026-05-02 17:35:43.030551: I metal_plugin/src/device/metal_device.cc:296] systemMemory: 16.00 GB
2026-05-02 17:35:43.030576: I metal_plugin/src/device/metal_device.cc:313] maxCacheSize: 5.92 GB
2026-05-02 17:35:43.030639: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:305] Could not identify NUMA node of platform GPU ID 0, defaulting to 0. Your kernel may not have been built with NUMA support.
2026-05-02 17:35:43.030663: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:271] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 0 MB memory) -> physical PluggableDevice (device: 0, name: METAL, pci bus id: <undefined>)
2026-05-02 17:35:43.739358: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:117] Plugin optimizer for device_type GPU is enabled.

      Saved model to: saved_models/cnn/cnn_f32_d32.keras
   -> Training CNN with 32 filters, 64 dense units...

KeyboardInterrupt:

In [ ]:
print("\nGenerating final predictions on Test Set...")
for name, model in best_models.items():
    if name == 'CNN':
        prob = model.predict(X_test_cnn, verbose=0).flatten()
        pred = (prob > 0.5).astype(int)
    elif name == 'Isolation Forest':
        raw = model.predict(X_test)
        pred = np.where(raw == -1, 1, 0)
        # Use decision_function as anomaly score (lower = more anomalous → negate for proba-like score)
        prob = -model.decision_function(X_test)
        # Normalise to [0,1] so roc_auc_score works
        prob = (prob - prob.min()) / (prob.max() - prob.min() + 1e-9)
    else:
        pred = model.predict(X_test)
        prob = model.predict_proba(X_test)[:, 1] if hasattr(model, 'predict_proba') else np.zeros(len(y_test))

    predictions[name] = {'pred': pred, 'prob': prob}

print("\n--- LOOP TUNING COMPLETE ---")

In [ ]:
from sklearn.linear_model import LogisticRegression

print("\n5. Tuning Logistic Regression with loops...")
best_lr_acc = 0
best_lr_model = None
best_lr_params = {}

for c_val in [0.01, 0.1, 1.0, 10.0]:
    for solver in ['lbfgs', 'liblinear']:
        model = LogisticRegression(C=c_val, solver=solver, max_iter=1000, random_state=42)
        model.fit(X_train_resampled, y_train_resampled)

        os.makedirs('saved_models/logistic_regression', exist_ok=True)
        filename = f"saved_models/logistic_regression/lr_C_{c_val}_solver_{solver}.joblib"
        joblib.dump(model, filename)
        print(f"Saved: {filename}")

        val_preds = model.predict(X_val)
        val_acc = accuracy_score(y_val, val_preds)

        if val_acc > best_lr_acc:
            best_lr_acc = val_acc
            best_lr_model = model
            best_lr_params = {'C': c_val, 'solver': solver}

best_models['Logistic Regression'] = best_lr_model
print(f"Best LR Params: {best_lr_params} | Val Accuracy: {best_lr_acc:.4f}")

In [ ]:
from xgboost import XGBClassifier

print("\n6. Tuning XGBoost with loops...")
best_xgb_acc = 0
best_xgb_model = None
best_xgb_params = {}

for lr in [0.05, 0.1, 0.3]:
    for max_depth in [3, 6, 9]:
        for n_estimators in [100, 200]:
            model = XGBClassifier(
                learning_rate=lr,
                max_depth=max_depth,
                n_estimators=n_estimators,
                use_label_encoder=False,
                eval_metric='logloss',
                random_state=42,
                verbosity=0
            )
            model.fit(X_train_resampled, y_train_resampled)

            os.makedirs('saved_models/xgboost', exist_ok=True)
            filename = f"saved_models/xgboost/xgb_lr{lr}_depth{max_depth}_n{n_estimators}.joblib"
            joblib.dump(model, filename)
            print(f"Saved: {filename}")

            val_preds = model.predict(X_val)
            val_acc = accuracy_score(y_val, val_preds)

            if val_acc > best_xgb_acc:
                best_xgb_acc = val_acc
                best_xgb_model = model
                best_xgb_params = {'learning_rate': lr, 'max_depth': max_depth, 'n_estimators': n_estimators}

best_models['XGBoost'] = best_xgb_model
print(f"Best XGBoost Params: {best_xgb_params} | Val Accuracy: {best_xgb_acc:.4f}")

In [ ]:
from sklearn.svm import SVC

print("\n7. Tuning SVM with loops...")
best_svm_acc = 0
best_svm_model = None
best_svm_params = {}

for C in [0.1, 1.0, 10.0]:
    for kernel in ['rbf', 'linear']:
        model = SVC(
            C=C,
            kernel=kernel,
            probability=True,   # needed for predict_proba / ROC AUC
            random_state=42
        )
        model.fit(X_train_resampled, y_train_resampled)

        os.makedirs('saved_models/svm', exist_ok=True)
        filename = f"saved_models/svm/svm_C{C}_kernel_{kernel}.joblib"
        joblib.dump(model, filename)
        print(f"Saved: {filename}")

        val_preds = model.predict(X_val)
        val_acc = accuracy_score(y_val, val_preds)

        if val_acc > best_svm_acc:
            best_svm_acc = val_acc
            best_svm_model = model
            best_svm_params = {'C': C, 'kernel': kernel}

best_models['SVM'] = best_svm_model
print(f"Best SVM Params: {best_svm_params} | Val Accuracy: {best_svm_acc:.4f}")

In [ ]:
from sklearn.ensemble import IsolationForest

print("\n8. Tuning Isolation Forest (anomaly detection baseline)...")
# Isolation Forest is unsupervised — train on benign-only to model normal traffic.
# Contamination param = expected fraction of anomalies in the training data.
best_if_f1 = 0
best_if_model = None
best_if_params = {}

# Extract benign samples from the ORIGINAL (pre-SMOTE) training set for a realistic anomaly model
benign_mask = (y_train == 0)
X_train_benign = X_train[benign_mask]

for n_estimators in [100, 200]:
    for contamination in [0.05, 0.1, 0.2]:
        model = IsolationForest(
            n_estimators=n_estimators,
            contamination=contamination,
            random_state=42
        )
        # Train on benign-only — the model learns what 'normal' looks like
        model.fit(X_train_benign)

        os.makedirs('saved_models/isolation_forest', exist_ok=True)
        filename = f"saved_models/isolation_forest/iforest_n{n_estimators}_c{contamination}.joblib"
        joblib.dump(model, filename)
        print(f"Saved: {filename}")

        # IsolationForest returns -1 (anomaly/malicious) or +1 (normal/benign)
        # Remap to binary labels: -1 → 1 (Malicious), +1 → 0 (Benign)
        raw_preds = model.predict(X_val)
        val_preds = np.where(raw_preds == -1, 1, 0)

        val_f1 = f1_score(y_val, val_preds, zero_division=0)

        if val_f1 > best_if_f1:
            best_if_f1 = val_f1
            best_if_model = model
            best_if_params = {'n_estimators': n_estimators, 'contamination': contamination}

# Store best IF model — note: no predict_proba; ROC AUC uses decision_function scores
best_models['Isolation Forest'] = best_if_model
print(f"Best IF Params: {best_if_params} | Val F1: {best_if_f1:.4f}")

#Results

In [ ]:

print("--- GENERATING FINAL RESULTS AND SAVING TO CSV ---")

results_list = []

for name in best_models.keys():
    pred = predictions[name]['pred']
    prob = predictions[name]['prob']

    acc = accuracy_score(y_test, pred)
    prec = precision_score(y_test, pred, zero_division=0)
    rec = recall_score(y_test, pred, zero_division=0)
    f1 = f1_score(y_test, pred, zero_division=0)

    try:
        auc_score = roc_auc_score(y_test, prob)
    except Exception:
        auc_score = "N/A"

    results_list.append({
        'Model': name,
        'Accuracy': acc,
        'Precision': prec,
        'Recall': rec,
        'F1 Score': f1,
        'ROC AUC': auc_score
    })

results_df = pd.DataFrame(results_list)

print("\n--- FINAL TEST SET EVALUATION ---")
display(results_df)

csv_filename = 'results.csv'
results_df.to_csv(csv_filename, index=False)
print(f"\n Results successfully saved to {csv_filename}!")

# using Optuna

In [ ]:
storage_name = "sqlite:///optuna_study.db"

In [ ]:
def xgb_objective(trial):
    lr = trial.suggest_float("learning_rate", 0.01, 0.5, log=True)
    max_depth = trial.suggest_int("max_depth", 3, 12)
    n_estimators = trial.suggest_int("n_estimators", 50, 300)
    subsample = trial.suggest_float("subsample", 0.5, 1.0)
    colsample_bytree = trial.suggest_float("colsample_bytree", 0.5, 1.0)

    model = XGBClassifier(
        learning_rate=lr,
        max_depth=max_depth,
        n_estimators=n_estimators,
        subsample=subsample,
        colsample_bytree=colsample_bytree,
        use_label_encoder=False,
        eval_metric='logloss',
        random_state=42,
        verbosity=0
    )
    model.fit(X_train_resampled, y_train_resampled)

    os.makedirs('saved_models/xgboost', exist_ok=True)
    filename = f"saved_models/xgboost/xgb_trial{trial.number}.joblib"
    joblib.dump(model, filename)

    val_preds = model.predict(X_val)
    return f1_score(y_val, val_preds, average='binary', zero_division=0)

XGB_study = optuna.create_study(
    study_name="XGBoost",
    storage=storage_name,
    direction="maximize",
    load_if_exists=True
)
XGB_study.optimize(xgb_objective, n_trials=20)
print(f"Best XGBoost F1:     {XGB_study.best_value:.4f}")
print(f"Best XGBoost Params: {XGB_study.best_params}")

In [ ]:
def svm_objective(trial):
    C = trial.suggest_float("C", 1e-2, 1e2, log=True)
    kernel = trial.suggest_categorical("kernel", ['rbf', 'linear'])
    gamma = trial.suggest_categorical("gamma", ['scale', 'auto']) if kernel == 'rbf' else 'scale'

    model = SVC(C=C, kernel=kernel, gamma=gamma, probability=True, random_state=42)
    model.fit(X_train_resampled, y_train_resampled)

    os.makedirs('saved_models/svm', exist_ok=True)
    filename = f"saved_models/svm/svm_trial{trial.number}.joblib"
    joblib.dump(model, filename)

    val_preds = model.predict(X_val)
    return f1_score(y_val, val_preds, average='binary', zero_division=0)

SVM_study = optuna.create_study(
    study_name="SVM",
    storage=storage_name,
    direction="maximize",
    load_if_exists=True
)
SVM_study.optimize(svm_objective, n_trials=15)
print(f"Best SVM F1:     {SVM_study.best_value:.4f}")
print(f"Best SVM Params: {SVM_study.best_params}")

In [ ]:
def iforest_objective(trial):
    n_estimators = trial.suggest_int("n_estimators", 50, 300)
    contamination = trial.suggest_float("contamination", 0.01, 0.4)
    max_features = trial.suggest_float("max_features", 0.3, 1.0)

    model = IsolationForest(
        n_estimators=n_estimators,
        contamination=contamination,
        max_features=max_features,
        random_state=42
    )
    model.fit(X_train_benign)  # train on benign-only

    os.makedirs('saved_models/isolation_forest', exist_ok=True)
    filename = f"saved_models/isolation_forest/iforest_trial{trial.number}.joblib"
    joblib.dump(model, filename)

    raw_preds = model.predict(X_val)
    val_preds = np.where(raw_preds == -1, 1, 0)
    return f1_score(y_val, val_preds, average='binary', zero_division=0)

IF_study = optuna.create_study(
    study_name="IsolationForest",
    storage=storage_name,
    direction="maximize",
    load_if_exists=True
)
IF_study.optimize(iforest_objective, n_trials=15)
print(f"Best IF F1:     {IF_study.best_value:.4f}")
print(f"Best IF Params: {IF_study.best_params}")

In [ ]:
def dt_objective(trial):
    depth = trial.suggest_categorical("max_depth", [None, 5, 10, 20])
    min_samples = trial.suggest_int("min_samples_split", 2, 10)
    _depth = depth if depth is not None else "None"

    model = DecisionTreeClassifier(max_depth=depth, min_samples_split=min_samples, random_state=42)
    model.fit(X_train_resampled, y_train_resampled)

    os.makedirs('saved_models/decision_tree', exist_ok=True)
    filename = f"saved_models/decision_tree/decision_tree_min_samples_split_{min_samples}_depth_{_depth}.joblib"
    joblib.dump(model, filename)
    print(f"Saved: {filename}")

    val_preds = model.predict(X_val)
    return accuracy_score(y_val, val_preds)

In [ ]:
def rt_objective(trial):
    n_trees = trial.suggest_int("n_estimators", 50, 200)
    depth = trial.suggest_categorical("max_depth", [None, 5, 10, 20, 30])

    model = RandomForestClassifier(n_estimators=n_trees, max_depth=depth, random_state=42)
    model.fit(X_train_resampled, y_train_resampled)

    _depth = depth if depth is not None else "None"
    filename = f"saved_models/random_forest/rf_trees_n_estimators_{n_trees}_max_depth_{_depth}.joblib"
    joblib.dump(model, filename)
    print(f"Saved: {filename}")

    val_preds = model.predict(X_val)
    return accuracy_score(y_val, val_preds)

In [ ]:
def MPL_objective(trial):
    hidden_layer_sizes_str = trial.suggest_categorical("hidden_layer_sizes", ["(50,)", "(100,)", "(50, 50)"])
    activation_func = trial.suggest_categorical("activation", ['relu', 'tanh'])
    hidden_layer = eval(hidden_layer_sizes_str)

    model = MLPClassifier(
        hidden_layer_sizes=hidden_layer,
        activation=activation_func,
        max_iter=300,
        random_state=42
    )
    model.fit(X_train_resampled, y_train_resampled)

    os.makedirs('saved_models/MLP', exist_ok=True)
    filename = f"saved_models/MLP/MLP_hidden_layer_sizes_{hidden_layer}_activation_func_{activation_func}.joblib"
    joblib.dump(model, filename)

    val_preds = model.predict(X_val)
    return accuracy_score(y_val, val_preds)

In [ ]:
def lr_objective(trial):
    c_val = trial.suggest_float("C", 1e-4, 1e2, log=True)
    solver = trial.suggest_categorical("solver", ["lbfgs", "liblinear"])

    model = LogisticRegression(C=c_val, solver=solver, max_iter=1000, random_state=42)
    model.fit(X_train_resampled, y_train_resampled)

    os.makedirs('saved_models/logistic_regression', exist_ok=True)
    filename = f"saved_models/logistic_regression/lr_C_{c_val:.4f}_solver_{solver}.joblib"
    joblib.dump(model, filename)

    val_preds = model.predict(X_val)
    return accuracy_score(y_val, val_preds)

LR_study = optuna.create_study(
    study_name="LogisticRegression",
    storage=storage_name,
    direction="maximize",
    load_if_exists=True
)

LR_study.optimize(lr_objective, n_trials=10)

print(f"Best LR Accuracy: {LR_study.best_value}")
print(f"Best LR Params:   {LR_study.best_params}")

In [ ]:
from tensorflow.keras.callbacks import EarlyStopping

def CNN_objective(trial):
    X_train_cnn = X_train_resampled.reshape(X_train_resampled.shape[0], X_train_resampled.shape[1], 1)
    X_val_cnn   = X_val.reshape(X_val.shape[0], X_val.shape[1], 1)

    filters     = trial.suggest_int("filters", 32, 128)
    dense_units = trial.suggest_int("dense_units", 32, 128)
    dropout_rate = trial.suggest_float("dropout", 0.2, 0.6)

    model = Sequential([
        Conv1D(filters=filters, kernel_size=3, activation='relu', input_shape=(X_train_cnn.shape[1], 1)),
        MaxPooling1D(pool_size=2),
        Flatten(),
        Dense(dense_units, activation='relu'),
        Dropout(dropout_rate),
        Dense(1, activation='sigmoid')
    ])
    model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

    early_stop = EarlyStopping(monitor='val_loss', patience=3, restore_best_weights=True)

    model.fit(
        X_train_cnn, y_train_resampled,
        epochs=50, batch_size=32, verbose=0,
        validation_data=(X_val_cnn, y_val),
        callbacks=[early_stop]
    )

    os.makedirs('saved_models/cnn', exist_ok=True)
    model_name = f"saved_models/cnn/cnn_f{filters}_d{dense_units}_t{trial.number}.keras"
    model.save(model_name)
    print(f"      Saved model to: {model_name}")

    val_probs = model.predict(X_val_cnn, verbose=0)
    val_preds = (val_probs > 0.5).astype(int)
    return f1_score(y_val, val_preds, average='binary')

In [ ]:

DT_study = optuna.create_study(
    study_name="DecisionTreeClassifier",
    storage=storage_name,
    direction="maximize",
    load_if_exists=True
)

DT_study.optimize(dt_objective, n_trials=20)

print(f"Best Accuracy: {DT_study.best_value}")
print(f"Best Params: {DT_study.best_params}")

[I 2026-05-02 18:08:18,906] A new study created in RDB with name: DecisionTreeClassifier
/var/folders/n9/hjzg_lkj5n1bp1v60850ymbh0000gn/T/ipykernel_14118/750741517.py:4: FutureWarning: suggest_int() got {'step'} as positional arguments but they were expected to be given as keyword arguments.
Positional arguments ['self', 'name', 'low', 'high', 'step', 'log'] in suggest_int() have been deprecated since v3.5.0. They will be replaced with the corresponding keyword arguments in v5.0.0, so please use the keyword specification instead. See https://github.com/optuna/optuna/releases/tag/v3.5.0 for details.
  min_samples = trial.suggest_int("min_samples_split", 2,5, 10)
/Users/sudiptahalder/Documents/school/TLS-Fingerprinting-Malicious-Detection/.venv/lib/python3.10/site-packages/optuna/distributions.py:684: UserWarning: The distribution is specified by [2, 5] and step=10, but the range is not divisible by `step`. It will be replaced with [2, 2].
  optuna_warn(
[I 2026-05-02 18:08:18,998] Trial 0 finished with value: 0.8071090820153269 and parameters: {'max_depth': 20, 'min_samples_split': 2}. Best is trial 0 with value: 0.8071090820153269.
/var/folders/n9/hjzg_lkj5n1bp1v60850ymbh0000gn/T/ipykernel_14118/750741517.py:4: FutureWarning: suggest_int() got {'step'} as positional arguments but they were expected to be given as keyword arguments.
Positional arguments ['self', 'name', 'low', 'high', 'step', 'log'] in suggest_int() have been deprecated since v3.5.0. They will be replaced with the corresponding keyword arguments in v5.0.0, so please use the keyword specification instead. See https://github.com/optuna/optuna/releases/tag/v3.5.0 for details.
  min_samples = trial.suggest_int("min_samples_split", 2,5, 10)
/Users/sudiptahalder/Documents/school/TLS-Fingerprinting-Malicious-Detection/.venv/lib/python3.10/site-packages/optuna/distributions.py:684: UserWarning: The distribution is specified by [2, 5] and step=10, but the range is not divisible by `step`. It will be replaced with [2, 2].
  optuna_warn(
[I 2026-05-02 18:08:19,076] Trial 1 finished with value: 0.8092287624327409 and parameters: {'max_depth': 10, 'min_samples_split': 2}. Best is trial 1 with value: 0.8092287624327409.
/var/folders/n9/hjzg_lkj5n1bp1v60850ymbh0000gn/T/ipykernel_14118/750741517.py:4: FutureWarning: suggest_int() got {'step'} as positional arguments but they were expected to be given as keyword arguments.
Positional arguments ['self', 'name', 'low', 'high', 'step', 'log'] in suggest_int() have been deprecated since v3.5.0. They will be replaced with the corresponding keyword arguments in v5.0.0, so please use the keyword specification instead. See https://github.com/optuna/optuna/releases/tag/v3.5.0 for details.
  min_samples = trial.suggest_int("min_samples_split", 2,5, 10)
/Users/sudiptahalder/Documents/school/TLS-Fingerprinting-Malicious-Detection/.venv/lib/python3.10/site-packages/optuna/distributions.py:684: UserWarning: The distribution is specified by [2, 5] and step=10, but the range is not divisible by `step`. It will be replaced with [2, 2].
  optuna_warn(
[I 2026-05-02 18:08:19,142] Trial 2 finished with value: 0.7932496331322354 and parameters: {'max_depth': 5, 'min_samples_split': 2}. Best is trial 1 with value: 0.8092287624327409.

Saved: saved_models/decision_tree/decision_tree_min_samples_split_2_depth_20.joblib
Saved: saved_models/decision_tree/decision_tree_min_samples_split_2_depth_10.joblib
Saved: saved_models/decision_tree/decision_tree_min_samples_split_2_depth_5.joblib

/var/folders/n9/hjzg_lkj5n1bp1v60850ymbh0000gn/T/ipykernel_14118/750741517.py:4: FutureWarning: suggest_int() got {'step'} as positional arguments but they were expected to be given as keyword arguments.
Positional arguments ['self', 'name', 'low', 'high', 'step', 'log'] in suggest_int() have been deprecated since v3.5.0. They will be replaced with the corresponding keyword arguments in v5.0.0, so please use the keyword specification instead. See https://github.com/optuna/optuna/releases/tag/v3.5.0 for details.
  min_samples = trial.suggest_int("min_samples_split", 2,5, 10)
/Users/sudiptahalder/Documents/school/TLS-Fingerprinting-Malicious-Detection/.venv/lib/python3.10/site-packages/optuna/distributions.py:684: UserWarning: The distribution is specified by [2, 5] and step=10, but the range is not divisible by `step`. It will be replaced with [2, 2].
  optuna_warn(
[I 2026-05-02 18:08:19,226] Trial 3 finished with value: 0.8071090820153269 and parameters: {'max_depth': 20, 'min_samples_split': 2}. Best is trial 1 with value: 0.8092287624327409.
/var/folders/n9/hjzg_lkj5n1bp1v60850ymbh0000gn/T/ipykernel_14118/750741517.py:4: FutureWarning: suggest_int() got {'step'} as positional arguments but they were expected to be given as keyword arguments.
Positional arguments ['self', 'name', 'low', 'high', 'step', 'log'] in suggest_int() have been deprecated since v3.5.0. They will be replaced with the corresponding keyword arguments in v5.0.0, so please use the keyword specification instead. See https://github.com/optuna/optuna/releases/tag/v3.5.0 for details.
  min_samples = trial.suggest_int("min_samples_split", 2,5, 10)
/Users/sudiptahalder/Documents/school/TLS-Fingerprinting-Malicious-Detection/.venv/lib/python3.10/site-packages/optuna/distributions.py:684: UserWarning: The distribution is specified by [2, 5] and step=10, but the range is not divisible by `step`. It will be replaced with [2, 2].
  optuna_warn(
[I 2026-05-02 18:08:19,309] Trial 4 finished with value: 0.8120006522093592 and parameters: {'max_depth': None, 'min_samples_split': 2}. Best is trial 4 with value: 0.8120006522093592.
/var/folders/n9/hjzg_lkj5n1bp1v60850ymbh0000gn/T/ipykernel_14118/750741517.py:4: FutureWarning: suggest_int() got {'step'} as positional arguments but they were expected to be given as keyword arguments.
Positional arguments ['self', 'name', 'low', 'high', 'step', 'log'] in suggest_int() have been deprecated since v3.5.0. They will be replaced with the corresponding keyword arguments in v5.0.0, so please use the keyword specification instead. See https://github.com/optuna/optuna/releases/tag/v3.5.0 for details.
  min_samples = trial.suggest_int("min_samples_split", 2,5, 10)
/Users/sudiptahalder/Documents/school/TLS-Fingerprinting-Malicious-Detection/.venv/lib/python3.10/site-packages/optuna/distributions.py:684: UserWarning: The distribution is specified by [2, 5] and step=10, but the range is not divisible by `step`. It will be replaced with [2, 2].
  optuna_warn(
[I 2026-05-02 18:08:19,385] Trial 5 finished with value: 0.8092287624327409 and parameters: {'max_depth': 10, 'min_samples_split': 2}. Best is trial 4 with value: 0.8120006522093592.

Saved: saved_models/decision_tree/decision_tree_min_samples_split_2_depth_20.joblib
Saved: saved_models/decision_tree/decision_tree_min_samples_split_2_depth_None.joblib
Saved: saved_models/decision_tree/decision_tree_min_samples_split_2_depth_10.joblib

/var/folders/n9/hjzg_lkj5n1bp1v60850ymbh0000gn/T/ipykernel_14118/750741517.py:4: FutureWarning: suggest_int() got {'step'} as positional arguments but they were expected to be given as keyword arguments.
Positional arguments ['self', 'name', 'low', 'high', 'step', 'log'] in suggest_int() have been deprecated since v3.5.0. They will be replaced with the corresponding keyword arguments in v5.0.0, so please use the keyword specification instead. See https://github.com/optuna/optuna/releases/tag/v3.5.0 for details.
  min_samples = trial.suggest_int("min_samples_split", 2,5, 10)
/Users/sudiptahalder/Documents/school/TLS-Fingerprinting-Malicious-Detection/.venv/lib/python3.10/site-packages/optuna/distributions.py:684: UserWarning: The distribution is specified by [2, 5] and step=10, but the range is not divisible by `step`. It will be replaced with [2, 2].
  optuna_warn(
[I 2026-05-02 18:08:19,462] Trial 6 finished with value: 0.8092287624327409 and parameters: {'max_depth': 10, 'min_samples_split': 2}. Best is trial 4 with value: 0.8120006522093592.
/var/folders/n9/hjzg_lkj5n1bp1v60850ymbh0000gn/T/ipykernel_14118/750741517.py:4: FutureWarning: suggest_int() got {'step'} as positional arguments but they were expected to be given as keyword arguments.
Positional arguments ['self', 'name', 'low', 'high', 'step', 'log'] in suggest_int() have been deprecated since v3.5.0. They will be replaced with the corresponding keyword arguments in v5.0.0, so please use the keyword specification instead. See https://github.com/optuna/optuna/releases/tag/v3.5.0 for details.
  min_samples = trial.suggest_int("min_samples_split", 2,5, 10)
/Users/sudiptahalder/Documents/school/TLS-Fingerprinting-Malicious-Detection/.venv/lib/python3.10/site-packages/optuna/distributions.py:684: UserWarning: The distribution is specified by [2, 5] and step=10, but the range is not divisible by `step`. It will be replaced with [2, 2].
  optuna_warn(
[I 2026-05-02 18:08:19,547] Trial 7 finished with value: 0.8071090820153269 and parameters: {'max_depth': 20, 'min_samples_split': 2}. Best is trial 4 with value: 0.8120006522093592.
/var/folders/n9/hjzg_lkj5n1bp1v60850ymbh0000gn/T/ipykernel_14118/750741517.py:4: FutureWarning: suggest_int() got {'step'} as positional arguments but they were expected to be given as keyword arguments.
Positional arguments ['self', 'name', 'low', 'high', 'step', 'log'] in suggest_int() have been deprecated since v3.5.0. They will be replaced with the corresponding keyword arguments in v5.0.0, so please use the keyword specification instead. See https://github.com/optuna/optuna/releases/tag/v3.5.0 for details.
  min_samples = trial.suggest_int("min_samples_split", 2,5, 10)
/Users/sudiptahalder/Documents/school/TLS-Fingerprinting-Malicious-Detection/.venv/lib/python3.10/site-packages/optuna/distributions.py:684: UserWarning: The distribution is specified by [2, 5] and step=10, but the range is not divisible by `step`. It will be replaced with [2, 2].
  optuna_warn(
[I 2026-05-02 18:08:19,631] Trial 8 finished with value: 0.8120006522093592 and parameters: {'max_depth': None, 'min_samples_split': 2}. Best is trial 4 with value: 0.8120006522093592.

Saved: saved_models/decision_tree/decision_tree_min_samples_split_2_depth_10.joblib
Saved: saved_models/decision_tree/decision_tree_min_samples_split_2_depth_20.joblib
Saved: saved_models/decision_tree/decision_tree_min_samples_split_2_depth_None.joblib

/var/folders/n9/hjzg_lkj5n1bp1v60850ymbh0000gn/T/ipykernel_14118/750741517.py:4: FutureWarning: suggest_int() got {'step'} as positional arguments but they were expected to be given as keyword arguments.
Positional arguments ['self', 'name', 'low', 'high', 'step', 'log'] in suggest_int() have been deprecated since v3.5.0. They will be replaced with the corresponding keyword arguments in v5.0.0, so please use the keyword specification instead. See https://github.com/optuna/optuna/releases/tag/v3.5.0 for details.
  min_samples = trial.suggest_int("min_samples_split", 2,5, 10)
/Users/sudiptahalder/Documents/school/TLS-Fingerprinting-Malicious-Detection/.venv/lib/python3.10/site-packages/optuna/distributions.py:684: UserWarning: The distribution is specified by [2, 5] and step=10, but the range is not divisible by `step`. It will be replaced with [2, 2].
  optuna_warn(
[I 2026-05-02 18:08:19,707] Trial 9 finished with value: 0.8092287624327409 and parameters: {'max_depth': 10, 'min_samples_split': 2}. Best is trial 4 with value: 0.8120006522093592.
/var/folders/n9/hjzg_lkj5n1bp1v60850ymbh0000gn/T/ipykernel_14118/750741517.py:4: FutureWarning: suggest_int() got {'step'} as positional arguments but they were expected to be given as keyword arguments.
Positional arguments ['self', 'name', 'low', 'high', 'step', 'log'] in suggest_int() have been deprecated since v3.5.0. They will be replaced with the corresponding keyword arguments in v5.0.0, so please use the keyword specification instead. See https://github.com/optuna/optuna/releases/tag/v3.5.0 for details.
  min_samples = trial.suggest_int("min_samples_split", 2,5, 10)
/Users/sudiptahalder/Documents/school/TLS-Fingerprinting-Malicious-Detection/.venv/lib/python3.10/site-packages/optuna/distributions.py:684: UserWarning: The distribution is specified by [2, 5] and step=10, but the range is not divisible by `step`. It will be replaced with [2, 2].
  optuna_warn(
[I 2026-05-02 18:08:19,789] Trial 10 finished with value: 0.8120006522093592 and parameters: {'max_depth': None, 'min_samples_split': 2}. Best is trial 4 with value: 0.8120006522093592.
/var/folders/n9/hjzg_lkj5n1bp1v60850ymbh0000gn/T/ipykernel_14118/750741517.py:4: FutureWarning: suggest_int() got {'step'} as positional arguments but they were expected to be given as keyword arguments.
Positional arguments ['self', 'name', 'low', 'high', 'step', 'log'] in suggest_int() have been deprecated since v3.5.0. They will be replaced with the corresponding keyword arguments in v5.0.0, so please use the keyword specification instead. See https://github.com/optuna/optuna/releases/tag/v3.5.0 for details.
  min_samples = trial.suggest_int("min_samples_split", 2,5, 10)
/Users/sudiptahalder/Documents/school/TLS-Fingerprinting-Malicious-Detection/.venv/lib/python3.10/site-packages/optuna/distributions.py:684: UserWarning: The distribution is specified by [2, 5] and step=10, but the range is not divisible by `step`. It will be replaced with [2, 2].
  optuna_warn(
[I 2026-05-02 18:08:19,870] Trial 11 finished with value: 0.8120006522093592 and parameters: {'max_depth': None, 'min_samples_split': 2}. Best is trial 4 with value: 0.8120006522093592.

Saved: saved_models/decision_tree/decision_tree_min_samples_split_2_depth_10.joblib
Saved: saved_models/decision_tree/decision_tree_min_samples_split_2_depth_None.joblib
Saved: saved_models/decision_tree/decision_tree_min_samples_split_2_depth_None.joblib

/var/folders/n9/hjzg_lkj5n1bp1v60850ymbh0000gn/T/ipykernel_14118/750741517.py:4: FutureWarning: suggest_int() got {'step'} as positional arguments but they were expected to be given as keyword arguments.
Positional arguments ['self', 'name', 'low', 'high', 'step', 'log'] in suggest_int() have been deprecated since v3.5.0. They will be replaced with the corresponding keyword arguments in v5.0.0, so please use the keyword specification instead. See https://github.com/optuna/optuna/releases/tag/v3.5.0 for details.
  min_samples = trial.suggest_int("min_samples_split", 2,5, 10)
/Users/sudiptahalder/Documents/school/TLS-Fingerprinting-Malicious-Detection/.venv/lib/python3.10/site-packages/optuna/distributions.py:684: UserWarning: The distribution is specified by [2, 5] and step=10, but the range is not divisible by `step`. It will be replaced with [2, 2].
  optuna_warn(
[I 2026-05-02 18:08:19,953] Trial 12 finished with value: 0.8120006522093592 and parameters: {'max_depth': None, 'min_samples_split': 2}. Best is trial 4 with value: 0.8120006522093592.
/var/folders/n9/hjzg_lkj5n1bp1v60850ymbh0000gn/T/ipykernel_14118/750741517.py:4: FutureWarning: suggest_int() got {'step'} as positional arguments but they were expected to be given as keyword arguments.
Positional arguments ['self', 'name', 'low', 'high', 'step', 'log'] in suggest_int() have been deprecated since v3.5.0. They will be replaced with the corresponding keyword arguments in v5.0.0, so please use the keyword specification instead. See https://github.com/optuna/optuna/releases/tag/v3.5.0 for details.
  min_samples = trial.suggest_int("min_samples_split", 2,5, 10)
/Users/sudiptahalder/Documents/school/TLS-Fingerprinting-Malicious-Detection/.venv/lib/python3.10/site-packages/optuna/distributions.py:684: UserWarning: The distribution is specified by [2, 5] and step=10, but the range is not divisible by `step`. It will be replaced with [2, 2].
  optuna_warn(
[I 2026-05-02 18:08:20,037] Trial 13 finished with value: 0.8120006522093592 and parameters: {'max_depth': None, 'min_samples_split': 2}. Best is trial 4 with value: 0.8120006522093592.
/var/folders/n9/hjzg_lkj5n1bp1v60850ymbh0000gn/T/ipykernel_14118/750741517.py:4: FutureWarning: suggest_int() got {'step'} as positional arguments but they were expected to be given as keyword arguments.
Positional arguments ['self', 'name', 'low', 'high', 'step', 'log'] in suggest_int() have been deprecated since v3.5.0. They will be replaced with the corresponding keyword arguments in v5.0.0, so please use the keyword specification instead. See https://github.com/optuna/optuna/releases/tag/v3.5.0 for details.
  min_samples = trial.suggest_int("min_samples_split", 2,5, 10)
/Users/sudiptahalder/Documents/school/TLS-Fingerprinting-Malicious-Detection/.venv/lib/python3.10/site-packages/optuna/distributions.py:684: UserWarning: The distribution is specified by [2, 5] and step=10, but the range is not divisible by `step`. It will be replaced with [2, 2].
  optuna_warn(
[I 2026-05-02 18:08:20,124] Trial 14 finished with value: 0.8120006522093592 and parameters: {'max_depth': None, 'min_samples_split': 2}. Best is trial 4 with value: 0.8120006522093592.

Saved: saved_models/decision_tree/decision_tree_min_samples_split_2_depth_None.joblib
Saved: saved_models/decision_tree/decision_tree_min_samples_split_2_depth_None.joblib
Saved: saved_models/decision_tree/decision_tree_min_samples_split_2_depth_None.joblib

/var/folders/n9/hjzg_lkj5n1bp1v60850ymbh0000gn/T/ipykernel_14118/750741517.py:4: FutureWarning: suggest_int() got {'step'} as positional arguments but they were expected to be given as keyword arguments.
Positional arguments ['self', 'name', 'low', 'high', 'step', 'log'] in suggest_int() have been deprecated since v3.5.0. They will be replaced with the corresponding keyword arguments in v5.0.0, so please use the keyword specification instead. See https://github.com/optuna/optuna/releases/tag/v3.5.0 for details.
  min_samples = trial.suggest_int("min_samples_split", 2,5, 10)
/Users/sudiptahalder/Documents/school/TLS-Fingerprinting-Malicious-Detection/.venv/lib/python3.10/site-packages/optuna/distributions.py:684: UserWarning: The distribution is specified by [2, 5] and step=10, but the range is not divisible by `step`. It will be replaced with [2, 2].
  optuna_warn(
[I 2026-05-02 18:08:20,208] Trial 15 finished with value: 0.8120006522093592 and parameters: {'max_depth': None, 'min_samples_split': 2}. Best is trial 4 with value: 0.8120006522093592.
/var/folders/n9/hjzg_lkj5n1bp1v60850ymbh0000gn/T/ipykernel_14118/750741517.py:4: FutureWarning: suggest_int() got {'step'} as positional arguments but they were expected to be given as keyword arguments.
Positional arguments ['self', 'name', 'low', 'high', 'step', 'log'] in suggest_int() have been deprecated since v3.5.0. They will be replaced with the corresponding keyword arguments in v5.0.0, so please use the keyword specification instead. See https://github.com/optuna/optuna/releases/tag/v3.5.0 for details.
  min_samples = trial.suggest_int("min_samples_split", 2,5, 10)
/Users/sudiptahalder/Documents/school/TLS-Fingerprinting-Malicious-Detection/.venv/lib/python3.10/site-packages/optuna/distributions.py:684: UserWarning: The distribution is specified by [2, 5] and step=10, but the range is not divisible by `step`. It will be replaced with [2, 2].
  optuna_warn(
[I 2026-05-02 18:08:20,273] Trial 16 finished with value: 0.7932496331322354 and parameters: {'max_depth': 5, 'min_samples_split': 2}. Best is trial 4 with value: 0.8120006522093592.
/var/folders/n9/hjzg_lkj5n1bp1v60850ymbh0000gn/T/ipykernel_14118/750741517.py:4: FutureWarning: suggest_int() got {'step'} as positional arguments but they were expected to be given as keyword arguments.
Positional arguments ['self', 'name', 'low', 'high', 'step', 'log'] in suggest_int() have been deprecated since v3.5.0. They will be replaced with the corresponding keyword arguments in v5.0.0, so please use the keyword specification instead. See https://github.com/optuna/optuna/releases/tag/v3.5.0 for details.
  min_samples = trial.suggest_int("min_samples_split", 2,5, 10)
/Users/sudiptahalder/Documents/school/TLS-Fingerprinting-Malicious-Detection/.venv/lib/python3.10/site-packages/optuna/distributions.py:684: UserWarning: The distribution is specified by [2, 5] and step=10, but the range is not divisible by `step`. It will be replaced with [2, 2].
  optuna_warn(
[I 2026-05-02 18:08:20,356] Trial 17 finished with value: 0.8120006522093592 and parameters: {'max_depth': None, 'min_samples_split': 2}. Best is trial 4 with value: 0.8120006522093592.

Saved: saved_models/decision_tree/decision_tree_min_samples_split_2_depth_None.joblib
Saved: saved_models/decision_tree/decision_tree_min_samples_split_2_depth_5.joblib
Saved: saved_models/decision_tree/decision_tree_min_samples_split_2_depth_None.joblib

/var/folders/n9/hjzg_lkj5n1bp1v60850ymbh0000gn/T/ipykernel_14118/750741517.py:4: FutureWarning: suggest_int() got {'step'} as positional arguments but they were expected to be given as keyword arguments.
Positional arguments ['self', 'name', 'low', 'high', 'step', 'log'] in suggest_int() have been deprecated since v3.5.0. They will be replaced with the corresponding keyword arguments in v5.0.0, so please use the keyword specification instead. See https://github.com/optuna/optuna/releases/tag/v3.5.0 for details.
  min_samples = trial.suggest_int("min_samples_split", 2,5, 10)
/Users/sudiptahalder/Documents/school/TLS-Fingerprinting-Malicious-Detection/.venv/lib/python3.10/site-packages/optuna/distributions.py:684: UserWarning: The distribution is specified by [2, 5] and step=10, but the range is not divisible by `step`. It will be replaced with [2, 2].
  optuna_warn(
[I 2026-05-02 18:08:20,440] Trial 18 finished with value: 0.8120006522093592 and parameters: {'max_depth': None, 'min_samples_split': 2}. Best is trial 4 with value: 0.8120006522093592.
/var/folders/n9/hjzg_lkj5n1bp1v60850ymbh0000gn/T/ipykernel_14118/750741517.py:4: FutureWarning: suggest_int() got {'step'} as positional arguments but they were expected to be given as keyword arguments.
Positional arguments ['self', 'name', 'low', 'high', 'step', 'log'] in suggest_int() have been deprecated since v3.5.0. They will be replaced with the corresponding keyword arguments in v5.0.0, so please use the keyword specification instead. See https://github.com/optuna/optuna/releases/tag/v3.5.0 for details.
  min_samples = trial.suggest_int("min_samples_split", 2,5, 10)
/Users/sudiptahalder/Documents/school/TLS-Fingerprinting-Malicious-Detection/.venv/lib/python3.10/site-packages/optuna/distributions.py:684: UserWarning: The distribution is specified by [2, 5] and step=10, but the range is not divisible by `step`. It will be replaced with [2, 2].
  optuna_warn(
[I 2026-05-02 18:08:20,508] Trial 19 finished with value: 0.7932496331322354 and parameters: {'max_depth': 5, 'min_samples_split': 2}. Best is trial 4 with value: 0.8120006522093592.

Saved: saved_models/decision_tree/decision_tree_min_samples_split_2_depth_None.joblib
Saved: saved_models/decision_tree/decision_tree_min_samples_split_2_depth_5.joblib
Best Accuracy: 0.8120006522093592
Best Params: {'max_depth': None, 'min_samples_split': 2}

In [ ]:

RT_study = optuna.create_study(
    study_name="RandomForestClassifier",
    storage=storage_name,
    direction="maximize",
    load_if_exists=True
)

RT_study.optimize(rt_objective, n_trials=20)

print(f"Best Accuracy: {RT_study.best_value}")
print(f"Best Params: {RT_study.best_params}")

[I 2026-05-02 18:08:25,797] A new study created in RDB with name: RandomForestClassifier
[I 2026-05-02 18:08:26,358] Trial 0 finished with value: 0.8075982390347302 and parameters: {'n_estimators': 58, 'max_depth': 30}. Best is trial 0 with value: 0.8075982390347302.

Saved: saved_models/random_forest/rf_trees_n_estimators_58_max_depth_30.joblib
Saved: saved_models/random_forest/rf_trees_n_estimators_58_max_depth_30.joblib

[I 2026-05-02 18:08:26,887] Trial 1 finished with value: 0.8134681232675689 and parameters: {'n_estimators': 54, 'max_depth': 20}. Best is trial 1 with value: 0.8134681232675689.

Saved: saved_models/random_forest/rf_trees_n_estimators_54_max_depth_20.joblib
Saved: saved_models/random_forest/rf_trees_n_estimators_54_max_depth_20.joblib

[I 2026-05-02 18:08:27,487] Trial 2 finished with value: 0.81363117560737 and parameters: {'n_estimators': 66, 'max_depth': 20}. Best is trial 2 with value: 0.81363117560737.

Saved: saved_models/random_forest/rf_trees_n_estimators_66_max_depth_20.joblib
Saved: saved_models/random_forest/rf_trees_n_estimators_66_max_depth_20.joblib

[I 2026-05-02 18:08:27,989] Trial 3 finished with value: 0.8167291700635904 and parameters: {'n_estimators': 70, 'max_depth': 10}. Best is trial 3 with value: 0.8167291700635904.

Saved: saved_models/random_forest/rf_trees_n_estimators_70_max_depth_10.joblib
Saved: saved_models/random_forest/rf_trees_n_estimators_70_max_depth_10.joblib

[I 2026-05-02 18:08:28,485] Trial 4 finished with value: 0.8079243437143323 and parameters: {'n_estimators': 52, 'max_depth': 30}. Best is trial 3 with value: 0.8167291700635904.

Saved: saved_models/random_forest/rf_trees_n_estimators_52_max_depth_30.joblib
Saved: saved_models/random_forest/rf_trees_n_estimators_52_max_depth_30.joblib

[I 2026-05-02 18:08:29,016] Trial 5 finished with value: 0.8162400130441871 and parameters: {'n_estimators': 76, 'max_depth': 10}. Best is trial 3 with value: 0.8167291700635904.

Saved: saved_models/random_forest/rf_trees_n_estimators_76_max_depth_10.joblib
Saved: saved_models/random_forest/rf_trees_n_estimators_76_max_depth_10.joblib

[I 2026-05-02 18:08:29,583] Trial 6 finished with value: 0.817870536442198 and parameters: {'n_estimators': 83, 'max_depth': 10}. Best is trial 6 with value: 0.817870536442198.

Saved: saved_models/random_forest/rf_trees_n_estimators_83_max_depth_10.joblib
Saved: saved_models/random_forest/rf_trees_n_estimators_83_max_depth_10.joblib

[I 2026-05-02 18:08:30,209] Trial 7 finished with value: 0.8168922224033915 and parameters: {'n_estimators': 65, 'max_depth': None}. Best is trial 6 with value: 0.817870536442198.

Saved: saved_models/random_forest/rf_trees_n_estimators_65_max_depth_None.joblib
Saved: saved_models/random_forest/rf_trees_n_estimators_65_max_depth_None.joblib

[I 2026-05-02 18:08:30,705] Trial 8 finished with value: 0.8315669329854883 and parameters: {'n_estimators': 95, 'max_depth': 5}. Best is trial 8 with value: 0.8315669329854883.

Saved: saved_models/random_forest/rf_trees_n_estimators_95_max_depth_5.joblib
Saved: saved_models/random_forest/rf_trees_n_estimators_95_max_depth_5.joblib

[I 2026-05-02 18:08:31,648] Trial 9 finished with value: 0.8098809717919452 and parameters: {'n_estimators': 100, 'max_depth': 30}. Best is trial 8 with value: 0.8315669329854883.

Saved: saved_models/random_forest/rf_trees_n_estimators_100_max_depth_30.joblib
Saved: saved_models/random_forest/rf_trees_n_estimators_100_max_depth_30.joblib

[I 2026-05-02 18:08:32,158] Trial 10 finished with value: 0.8299364095874776 and parameters: {'n_estimators': 100, 'max_depth': 5}. Best is trial 8 with value: 0.8315669329854883.

Saved: saved_models/random_forest/rf_trees_n_estimators_100_max_depth_5.joblib
Saved: saved_models/random_forest/rf_trees_n_estimators_100_max_depth_5.joblib

[I 2026-05-02 18:08:32,704] Trial 11 finished with value: 0.8299364095874776 and parameters: {'n_estimators': 100, 'max_depth': 5}. Best is trial 8 with value: 0.8315669329854883.

Saved: saved_models/random_forest/rf_trees_n_estimators_100_max_depth_5.joblib
Saved: saved_models/random_forest/rf_trees_n_estimators_100_max_depth_5.joblib

[I 2026-05-02 18:08:33,167] Trial 12 finished with value: 0.830914723626284 and parameters: {'n_estimators': 90, 'max_depth': 5}. Best is trial 8 with value: 0.8315669329854883.

Saved: saved_models/random_forest/rf_trees_n_estimators_90_max_depth_5.joblib
Saved: saved_models/random_forest/rf_trees_n_estimators_90_max_depth_5.joblib

[I 2026-05-02 18:08:33,631] Trial 13 finished with value: 0.8305886189466819 and parameters: {'n_estimators': 89, 'max_depth': 5}. Best is trial 8 with value: 0.8315669329854883.

Saved: saved_models/random_forest/rf_trees_n_estimators_89_max_depth_5.joblib
Saved: saved_models/random_forest/rf_trees_n_estimators_89_max_depth_5.joblib

[I 2026-05-02 18:08:34,127] Trial 14 finished with value: 0.8305886189466819 and parameters: {'n_estimators': 91, 'max_depth': 5}. Best is trial 8 with value: 0.8315669329854883.

Saved: saved_models/random_forest/rf_trees_n_estimators_91_max_depth_5.joblib
Saved: saved_models/random_forest/rf_trees_n_estimators_91_max_depth_5.joblib

[I 2026-05-02 18:08:34,585] Trial 15 finished with value: 0.8305886189466819 and parameters: {'n_estimators': 89, 'max_depth': 5}. Best is trial 8 with value: 0.8315669329854883.

Saved: saved_models/random_forest/rf_trees_n_estimators_89_max_depth_5.joblib
Saved: saved_models/random_forest/rf_trees_n_estimators_89_max_depth_5.joblib

[I 2026-05-02 18:08:35,310] Trial 16 finished with value: 0.811511495189956 and parameters: {'n_estimators': 78, 'max_depth': None}. Best is trial 8 with value: 0.8315669329854883.

Saved: saved_models/random_forest/rf_trees_n_estimators_78_max_depth_None.joblib
Saved: saved_models/random_forest/rf_trees_n_estimators_78_max_depth_None.joblib

[I 2026-05-02 18:08:35,779] Trial 17 finished with value: 0.8314038806456873 and parameters: {'n_estimators': 93, 'max_depth': 5}. Best is trial 8 with value: 0.8315669329854883.

Saved: saved_models/random_forest/rf_trees_n_estimators_93_max_depth_5.joblib
Saved: saved_models/random_forest/rf_trees_n_estimators_93_max_depth_5.joblib

[I 2026-05-02 18:08:36,198] Trial 18 finished with value: 0.8287950432088701 and parameters: {'n_estimators': 82, 'max_depth': 5}. Best is trial 8 with value: 0.8315669329854883.

Saved: saved_models/random_forest/rf_trees_n_estimators_82_max_depth_5.joblib
Saved: saved_models/random_forest/rf_trees_n_estimators_82_max_depth_5.joblib

[I 2026-05-02 18:08:36,686] Trial 19 finished with value: 0.8304255666068808 and parameters: {'n_estimators': 96, 'max_depth': 5}. Best is trial 8 with value: 0.8315669329854883.

Saved: saved_models/random_forest/rf_trees_n_estimators_96_max_depth_5.joblib
Saved: saved_models/random_forest/rf_trees_n_estimators_96_max_depth_5.joblib
Best Accuracy: 0.8315669329854883
Best Params: {'n_estimators': 95, 'max_depth': 5}

In [ ]:
# 5. Run the Study
ML_study = optuna.create_study(
    study_name="MLP_Search",
    storage=storage_name,
    direction="maximize",
    load_if_exists=True
)

ML_study.optimize(MPL_objective, n_trials=6) # 6 trials covers your exact original loop

print(f"Best MLP Params: {ML_study.best_params} | Val Accuracy: {ML_study.best_value:.4f}")

[I 2026-05-02 18:38:33,206] Using an existing study with name 'MLP_Search' instead of creating a new one.

(50, 50)

[I 2026-05-02 18:39:01,866] Trial 6 finished with value: 0.7958584705690527 and parameters: {'hidden_layer_sizes': '(50, 50)', 'activation': 'tanh'}. Best is trial 0 with value: 0.796510679928257.

(50, 50)

[I 2026-05-02 18:39:18,034] Trial 7 finished with value: 0.7886841676178054 and parameters: {'hidden_layer_sizes': '(50, 50)', 'activation': 'relu'}. Best is trial 0 with value: 0.796510679928257.

(50,)

[I 2026-05-02 18:39:37,282] Trial 8 finished with value: 0.8129789662481657 and parameters: {'hidden_layer_sizes': '(50,)', 'activation': 'relu'}. Best is trial 8 with value: 0.8129789662481657.

(100,)

[I 2026-05-02 18:40:03,294] Trial 9 finished with value: 0.7917821620740257 and parameters: {'hidden_layer_sizes': '(100,)', 'activation': 'relu'}. Best is trial 8 with value: 0.8129789662481657.

(50,)

[I 2026-05-02 18:40:25,060] Trial 10 finished with value: 0.8129789662481657 and parameters: {'hidden_layer_sizes': '(50,)', 'activation': 'relu'}. Best is trial 8 with value: 0.8129789662481657.

(50,)

[I 2026-05-02 18:40:46,774] Trial 11 finished with value: 0.8129789662481657 and parameters: {'hidden_layer_sizes': '(50,)', 'activation': 'relu'}. Best is trial 8 with value: 0.8129789662481657.

Best MLP Params: {'hidden_layer_sizes': '(50,)', 'activation': 'relu'} | Val Accuracy: 0.8130

In [ ]:
CNN_study = optuna.create_study(
    study_name="CNN",
    storage=storage_name,
    direction="maximize",
    load_if_exists=True
)

CNN_study.optimize(CNN_objective, n_trials=4)

print(f"Best Accuracy: {CNN_study.best_value}")
print(f"Best Params: {CNN_study.best_params}")

[I 2026-05-02 18:54:33,771] Using an existing study with name 'CNN' instead of creating a new one.
/Users/sudiptahalder/Documents/school/TLS-Fingerprinting-Malicious-Detection/.venv/lib/python3.10/site-packages/keras/src/layers/convolutional/base_conv.py:113: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

      Saved model to: saved_models/cnn/cnn_f63_d60.keras

[I 2026-05-02 18:55:43,368] Trial 4 finished with value: 0.8592811215347317 and parameters: {'filters': 63, 'dense_units': 60}. Best is trial 4 with value: 0.8592811215347317.
/Users/sudiptahalder/Documents/school/TLS-Fingerprinting-Malicious-Detection/.venv/lib/python3.10/site-packages/keras/src/layers/convolutional/base_conv.py:113: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

      Saved model to: saved_models/cnn/cnn_f59_d39.keras

[I 2026-05-02 18:56:52,722] Trial 5 finished with value: 0.8586638830897704 and parameters: {'filters': 59, 'dense_units': 39}. Best is trial 4 with value: 0.8592811215347317.
/Users/sudiptahalder/Documents/school/TLS-Fingerprinting-Malicious-Detection/.venv/lib/python3.10/site-packages/keras/src/layers/convolutional/base_conv.py:113: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

      Saved model to: saved_models/cnn/cnn_f59_d44.keras

[I 2026-05-02 18:58:01,938] Trial 6 finished with value: 0.8742994395516414 and parameters: {'filters': 59, 'dense_units': 44}. Best is trial 6 with value: 0.8742994395516414.
/Users/sudiptahalder/Documents/school/TLS-Fingerprinting-Malicious-Detection/.venv/lib/python3.10/site-packages/keras/src/layers/convolutional/base_conv.py:113: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

      Saved model to: saved_models/cnn/cnn_f33_d61.keras

[I 2026-05-02 18:59:10,404] Trial 7 finished with value: 0.8588524415001603 and parameters: {'filters': 33, 'dense_units': 61}. Best is trial 6 with value: 0.8742994395516414.

Best Accuracy: 0.8742994395516414
Best Params: {'filters': 59, 'dense_units': 44}

# Model Interpretability with LIME
Explain individual predictions from the best Random Forest model using `LimeTabularExplainer`.

In [ ]:
# ── Reconstruct full feature name list ──────────────────────────────────────
# 1. Numeric column names (in order they were passed to the numeric pipeline)
numeric_feature_names = list(X_trainR.select_dtypes(include=[np.number]).columns)

# 2. One-Hot encoded feature names from the categorical pipeline
ohe_feature_names = list(
    categorical_pipeline.named_steps['encoder'].get_feature_names_out(hotencode_labels)
)

# 3. Ordinal / label-encoded column names
ordinal_feature_names = list(label_trainR.columns)

# Concatenate in the EXACT same order used when building X_train
all_feature_names = numeric_feature_names + ohe_feature_names + ordinal_feature_names
print(f"Total features: {len(all_feature_names)}")
print(f"X_train shape:  {X_train_resampled.shape[1]} (should match)")

In [ ]:
# ── LIME Explainer ──────────────────────────────────────────────────────────
explainer = lime.lime_tabular.LimeTabularExplainer(
    training_data=X_train_resampled,
    feature_names=all_feature_names,
    class_names=['Benign', 'Malicious'],
    mode='classification',
    random_state=42
)

# Pick a sample from the test set (index 0 — change as needed)
sample_idx = 0
test_instance = X_test[sample_idx]

# Explain using the best Random Forest model
explanation = explainer.explain_instance(
    data_row=test_instance,
    predict_fn=best_models['Random Forest'].predict_proba,
    num_features=15  # top-15 most influential features
)

true_label = y_test[sample_idx]
pred_label = best_models['Random Forest'].predict([test_instance])[0]
print(f"True label: {'Malicious' if true_label else 'Benign'} | "
      f"Predicted: {'Malicious' if pred_label else 'Benign'}")

explanation.show_in_notebook(show_table=True)